name: palestra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.2
  file_picker: ^10.3.10
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  table_calendar: ^3.2.0
  vibration: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

# CONFIGURAZIONE ICONA
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/playstore.png"

# CONFIGURAZIONE SCHERMATA DI APERTURA (Splash Screen)
flutter_native_splash:
  color: "#121212"
  image: "assets/playstore.png"
  android_12:
    image: "assets/playstore.png"
    icon_background_color: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/playstore.png
    - assets/esercizi_it.json
    - assets/esercizi_master_tiger.json