// 🐯 DIZIONARIO BLINDATO ANTI-DOPPIONI 🐯
class DizionarioEsercizi {
  static const Map<String, String> daIngleseAItaliano = {
    'Adduttore/Groin': 'Stretching Adduttori con Partner',
    'Bicicletta in aria': 'Crunch Bicicletta (Air Bike)',
    'Tendine quadricipiti in quattro': 'Stretching Quadricipiti in Quadrupedia',
    'Curl alternato a martello': 'Hammer Curl Alternato con Manubri',
    'Alternate Heel Touchers': 'Heel Touch Alternato',
    'Alternate Incline Dumbbell Curl': 'Curl Alternato con Manubri su Panca Inclinata',
    'Alternate Leg Diagonal Bound': 'Balzi Diagonali Alternati',
    'Alternating Cable Shoulder Press': 'Shoulder Press Alternata ai Cavi',
    'Alternating Deltoid Raise': 'Alzate Deltoidi Alternate Frontali e Laterali',
    'Esercizio con l\'ausilio della corda': 'Rotazioni delle Caviglie',
    'Good Morning con la corda': 'Stretching Piriforme da Supino',
    'Good Morning con la corda (Tirare attraverso)': 'Rilascio Miofasciale Tibiale Anteriore',
    'Adduzioni di bacino con la corda': 'Anti-Gravity Press',
    'Tira la corda a parte': 'Circonduzioni delle Braccia',
    'Back Flyes - Con Banda': 'Alzate Posteriori con Elastico',
    'Trascinamento all\'indietro': 'Trascinamento Slitta all\'Indietro',
    'Lancio di Palla Medica all\'indietro': 'Lancio della Palla Medica all\'Indietro',
    'Parete di Equilibrio': 'Equilibrio su Proprioceptive Board',
    'Sollevamento di Palla per Cosce': 'Leg Curl su Fitball',
    'Esercizio Cervicale con Cintura di Resistenza': 'Skull Crusher con elastico',
    'Rollout con Barra Olimpica': 'Ab Rollout con bilanciere',
    'Rollout con Barra Olimpica - a ginocchia': 'Ab Rollout con bilanciere (ginocchia a terra)',
    'Esercizio di Pressa a Banco con Barra - Presa Media': 'Panca piana con bilanciere (presa media)',
    'Sollevamento di Barra con Bicipiti': 'Curl con bilanciere',
    'Band Assisted Pull-Up': 'Trazioni Assistite con Elastico',
    'Band Good Morning': 'Good Morning con Elastico',
    'Band Good Morning (Pull Through)': 'Pull Through con Elastico',
    'Band Hip Adductions': 'Adduzioni dell\'Anca con Elastico',
    'Band Skull Crusher': 'Skull Crusher con Elastico',
    'Barbell Ab Rollout': 'Ab Rollout con Bilanciere',
    'Barbell Ab Rollout - On Knees': 'Ab Rollout con Bilanciere in Ginocchio',
    'Barbell Bench Press - Medium Grip': 'Panca Piana con Bilanciere - Presa Media',
    'Barbell Curl': 'Curl con Bilanciere',
    'Barbell Curls Lying Against An Incline': 'Spider Curl con Bilanciere su Panca Inclinata',
    'Barbell Deadlift': 'Stacco da Terra con Bilanciere',
    'Barbell Full Squat': 'Squat Completo con Bilanciere',
    'Barbell Glute Bridge': 'Ponte Glutei con Bilanciere',
    'Barbell Hip Thrust': 'Hip Thrust con Bilanciere',
    'Barbell Incline Bench Press - Medium Grip': 'Panca Inclinata con Bilanciere - Presa Media',
    'Barbell Incline Shoulder Raise': 'Scrollate Scapolari su Panca Inclinata con Bilanciere',
    'Barbell Lunge': 'Affondi con Bilanciere',
    'Barbell Rear Delt Row': 'Rematore con Bilanciere per Deltoidi Posteriori',
    'Barbell Rollout from Bench': 'Barbell Rollout da Panca',
    'Barbell Seated Calf Raise': 'Calf Raise Seduto con Bilanciere',
    'Barbell Shoulder Press': 'Shoulder Press con Bilanciere da Seduto',
    'Barbell Shrug': 'Scrollate con Bilanciere',
    'Barbell Shrug Behind The Back': 'Scrollate con Bilanciere Dietro la Schiena',
    'Barbell Side Bend': 'Side Bend con Bilanciere',
    'Barbell Side Split Squat': 'Squat Laterale con Bilanciere',
    'Barbell Squat': 'Squat con Bilanciere',
    'Barbell Step Ups': 'Step Up con Bilanciere',
    'Barbell Walking Lunge': 'Affondi in Camminata con Bilanciere',
    'Battling Ropes': 'Battle Ropes',
    'Bear Crawl Sled Drags': 'Trascinamento Slitta in Bear Crawl',
    'Behind Head Chest Stretch': 'Stretching Pettorali con Assistenza',
    'Bench Dips': 'Dip alla Panca',
    'Bench Jump': 'Salto sulla Panca',
    'Bench Press - Powerlifting': 'Panca Piana Powerlifting',
    'Bench Press - Con le cinture': 'Panca Piana con Catene',
    'Bench Sprint': 'Step-up Esplosivo su Panca',
    'Bent-Arm Barbell Pullover': 'Pullover con Bilanciere a Braccia Flesse',
    'Bent-Arm Dumbbell Pullover': 'Pullover con Manubrio a Braccia Flesse',
    'Bent-Knee Hip Raise': 'Reverse Crunch a Ginocchia Flesse',
    'Bent Over Barbell Row': 'Rematore con Bilanciere',
    'Bent Over Dumbbell Rear Delt Raise With Head On Bench': 'Alzate Posteriori con Fronte su Panca',
    'Bent Over Low-Pulley Side Lateral': 'Alzate Laterali al Cavo Basso Busto Flesso',
    'Bent Over One-Arm Long Bar Row': 'Rematore Landmine a un Braccio',
    'Bent Over Two-Dumbbell Row With Palms In': 'Rematore con due manubri presa neutra',
    'Bicicletta': 'Ciclismo',
    'Bicicletta, Stazionaria': 'Cyclette',
    'Body Tricep Press': 'Estensioni tricipiti al rack',
    'Bodyweight Flyes': 'Croci a terra con bilancieri EZ',
    'Bodyweight Mid Row': 'Rematore inverso a corpo libero',
    'Bodyweight Squat': 'Squat a corpo libero',
    'Bodyweight Walking Lunge': 'Affondi in movimento a corpo libero',
    'Bosu Ball Cable Crunch With Side Bends': 'Crunch al cavo su Bosu con flessioni laterali',
    'Bottoms-Up Clean From The Hang Position': 'Bottoms-Up Clean dalla posizione Hang',
    'Bottoms Up': 'Bottoms Up (Reverse Crunch con sollevamento bacino)',
    'Box Jump (Multiple Response)': 'Box Jump (Ripetizioni multiple)',
    'Box Skip': 'Box Skip (Salti alternati su Box)',
    'Box Squat': 'Box Squat con bilanciere',
    'Brachialis-SMR': 'Rilascio miofasciale del brachiale (SMR)',
    'Bradford/Rocky Presses': 'Bradford Press (Military Press avanti e dietro)',
    'Butt-Ups': 'Plank con Sollevamento del Bacino',
    'Butt Lift (Bridge)': 'Ponte per i Glutei',
    'Butterfly': 'Pec Deck (Butterfly Machine)',
    'Cable Chest Press': 'Spinte al Cavo Seduto',
    'Cable Crossover': 'Croci ai Cavi Alti',
    'Cable Crunch': 'Crunch al Cavo Alto in Ginocchio',
    'Cable Deadlifts': 'Stacchi ai Cavi',
    'Cable Hammer Curls - Rope Attachment': 'Hammer Curl ai Cavi con Corda',
    'Cable Hip Adduction': 'Adduzioni ai Cavi',
    'Cable Incline Pushdown': 'Pullover ai Cavi su Panca Inclinata',
    'Cable Incline Triceps Extension': 'Estensioni Tricipiti ai Cavi su Panca Inclinata',
    'Cable Internal Rotation': 'Rotazione Interna ai Cavi',
    'Cable Iron Cross': 'Croci ai Cavi (Ferro da Stiro)',
    'Cable Judo Flip': 'Schiacciata Judo ai Cavi',
    'Cable Lying Triceps Extension': 'Estensioni Tricipiti sdraiato ai Cavi',
    'Cable One Arm Tricep Extension': 'Estensioni Tricipiti ai Cavi a Un Braccio',
    'Cable Preacher Curl': 'Curl al Panca Scott ai Cavi',
    'Cable Rear Delt Fly': 'Alzate Posteriori ai Cavi',
    'Cable Reverse Crunch': 'Crunch Inversi ai Cavi',
    'Cable Rope Overhead Triceps Extension': 'Estensioni Tricipiti Sopra la Testa con Corda ai Cavi',
    'Cable Rope Rear-Delt Rows': 'Trazioni Corde Posteriori Deltoidi ai Cavi',
    'Cable Russian Twists': 'Torsioni Russe ai Cavi con Corda',
    'Cable Seated Crunch': 'Crunch ai Cavi da Seduto',
    'Cable Shoulder Press': 'Distensioni per le Spalle ai Cavi',
    'Cable Shrugs': 'Scrollate ai Cavi',
    'Cable Wrist Curl': 'Curl Avambracci al Cavo',
    'Calf-Machine Shoulder Shrug': 'Scrollate con Macchina Polpacci',
    'Calf Press': 'Spinte Polpacci (Macchina)',
    'Calf Press On The Leg Press Machine': 'Spinte Polpacci su Leg Press',
    'Calf Raise On A Dumbbell': 'Sollevamento Polpacci su Manubrio',
    'Calf Raises - With Bands': 'Alzate di polpacci con elastici',
    'Calf Stretch Elbows Against Wall': 'Stretching polpacci con gomiti al muro',
    'Calf Stretch Hands Against Wall': 'Stretching polpacci con mani al muro',
    'Calves-SMR': 'Auto-massaggio polpacci con rullo',
    'Car Deadlift': 'Stacco da terra con auto',
    'Car Drivers': 'Rotazione Manubrio (Volante)',
    'Carioca Quick Step': 'Passi Veloci Laterali',
    'Cat Stretch': 'Stretching Felino',
    'Catch and Overhead Throw': 'Ricezione e Lancio Sopra la Testa',
    'Chain Handle Extension': 'Estensioni Maniglie a Catena',
    'Chain Press': 'Panca a Catene',
    'Chair Leg Extended Stretch': 'Stiramento Gamba Estesa su Sedia',
    'Chair Lower Back Stretch': 'Stiramento Schiena Bassa su Sedia',
    'Chair Squat': 'Squat su Sedia',
    'Chair Upper Body Stretch': 'Stiramento Parte Superiore del Corpo su Sedia',
    'Chest And Front Of Shoulder Stretch': 'Stretching Pettorali e Spalle Anteriori',
    'Chest Push from 3 point stance': 'Spinta con Palla Medica (da 3 punti)',
    'Chest Push (multiple response)': 'Spinta con Palla Medica (multi-risposta)',
    'Chest Push (single response)': 'Spinta con Palla Medica (singola risposta)',
    'Chest Push con rilascio di corsa': 'Spinta con Palla Medica e Rilascio in Corsa',
    'Chest Stretch su pallone di esercizio': 'Stiramento Pettorali su Palla Svizzera',
    'Posizione del bambino': 'Posizione del Bambino',
    'Chin-Up': 'Trazioni alla Sbarra (Supine)',
    'Chin To Chest Stretch': 'Stiramento Mento al Petto',
    'Circus Bell': 'Circus Bell Swing',
    'Clean Deadlift': 'Stacco Clean',
    'Clean Shrug': 'Scrollate Clean',
    'Close-Grip Barbell Bench Press': 'Panca Piana Presa Stretta con Bilanciere',
    'Close-Grip Dumbbell Press': 'Panca con Manubri Presa Stretta',
    'Close-Grip EZ-Bar Curl con cinghia': 'Curl EZ Bar Presa Stretta con Elastico',
    'Close-Grip EZ-Bar Press': 'Spinte EZ Bar Presa Stretta',
    'Close-Grip EZ Bar Curl': 'Curl EZ Bar Presa Stretta',
    'Close-Grip Front Lat Pulldown': 'Lat Machine Presa Stretta Avanzata',
    'Close-Grip Push-Up off of a Dumbbell': 'Piegamenti a Presa Stretta su Manubrio',
    'Cocoons': 'Coccoons',
    'Concentration Curls': 'Curl a Martello',
    'Cross-Body Crunch': 'Crunch Incrociato',
    'Cross Body Hammer Curl': 'Curl a Martello Incrociato',
    'Crossover Reverse Lunge': 'Affondo Inverso Incrociato',
    'Crucifix': 'Crocefisso Statico',
    'Crunch - Mani in Cima': 'Crunch con Mani Sopra la Testa',
    'Crunch - Gambe Sulle Palle di Esercizio': 'Crunch a terra con palla svizzera',
    'Crunches': 'Crunch a terra',
    'Dancer\'s Stretch': 'Stretching da danzatrice',
    'Dead Bug': 'Vespa morta',
    'Deadlift con cinghie': 'Stacco da terra con elastici',
    'Deadlift con catene': 'Stacco da Terra con Catene',
    'Decline Barbell Bench Press': 'Panca Piana Inclinata Negativa con Bilanciere',
    'Decline Close-Grip Bench To Skull Crusher': 'Panca Piana Inclinata Negativa Presa Stretta per Estensioni Tricipiti',
    'Decline Crunch': 'Crunch Inclinato Negativo',
    'Decline Dumbbell Bench Press': 'Panca Piana Inclinata Negativa con Manubri',
    'Decline Dumbbell Flyes': 'Croci con Manubri su Panca Declina',
    'Decline EZ Bar Triceps Extension': 'Estensioni Tricipiti con Bilanciere EZ su Panca Declina',
    'Decline Oblique Crunch': 'Crunch Obliqui su Panca Declina',
    'Decline Push-Up': 'Piegamenti a Terra su Panca Declina',
    'Decline Reverse Crunch': 'Crunch Inversi su Panca Declina',
    'Decline Smith Press': 'Panca Smith Inclinata Negativa',
    'Deficit Deadlift': 'Stacco da Terra con Deficit',
    'Depth Jump Leap': 'Salto in Profondità Esteso',
    'Dip Machine': 'Macchina Dip',
    'Dips - Chest Version': 'Dip - Versione Petto',
    'Dips - Triceps Version': 'Dips tricipiti',
    'Donkey Calf Raises': 'Sollevamenti polpacci da asino',
    'Clean': 'Clean alternato con doppio kettlebell',
    'Double Kettlebell Jerk': 'Jerk con doppio kettlebell',
    'Double Kettlebell Push Press': 'Push Press con doppio kettlebell',
    'Double Kettlebell Snatch': 'Slancio Kettlebell Doppio',
    'Double Kettlebell Windmill': 'Mulino a Vento con Kettlebell Doppio',
    'Double Leg Butt Kick': 'Calcio al Gluteo a Gambe Unite',
    'Downward Facing Balance': 'Equilibrio a Testa in Giù',
    'Drag Curl': 'Curl a Strappo',
    'Drop Push': 'Push-up sulle pedane',
    'Dumbbell Alternate Bicep Curl': 'Curl a martello alternato con manubri',
    'Dumbbell Bench Press': 'Panca piana con manubri',
    'Dumbbell Bench Press con Presa Neutrale': 'Panca piana con manubri presa neutra',
    'Dumbbell Bicep Curl': 'Curl per bicipiti con manubri',
    'Dumbbell Floor Press': 'Panca a Terra con Manubri',
    'Dumbbell Flyes': 'Croci con Manubri su Panca Piana',
    'Dumbbell Incline Row': 'Rematore con Manubri su Panca Inclinata',
    'Dumbbell Incline Shoulder Raise': 'Alzate Laterali con Manubri su Panca Inclinata',
    'Dumbbell Lunges': 'Affondi con Manubri',
    'Dumbbell Lying One-Arm Rear Lateral Raise': 'Alzate Laterali Posteriori Manubrio su Panca Inclinata (un braccio)',
    'Dumbbell Lying Pronation': 'Pronazione Manubrio da Sdraiato',
    'Dumbbell Lying Rear Lateral Raise': 'Alzate Laterali Posteriori Manubri su Panca Inclinata',
    'Dumbbell Lying Supination': 'Supinazione Manubrio da Sdraiato',
    'Dumbbell One-Arm Triceps Extension': 'Estensione Tricipiti Manubrio (un braccio)',
    'Dumbbell One-Arm Upright Row': 'Tirata Alta con Manubrio Singolo',
    'Dumbbell Prone Incline Curl': 'Curl a Inclinazione su Panca con Manubri (Prone)',
    'Dumbbell Raise': 'Alzate Laterali con Manubri',
    'Dumbbell Scaption': 'Alzate in Scapulazione con Manubri',
    'Dumbbell Seated Box Jump': 'Salto dal Seduto con Box e Manubri',
    'Dumbbell Seated One-Leg Calf Raise': 'Alzate ai polpacci seduto con manubrio su una gamba',
    'Dumbbell Shoulder Press': 'Military press con manubri',
    'Dumbbell Shrug': 'Scrollate con manubri',
    'Dumbbell Side Bend': 'Flessioni laterali con manubrio',
    'Rotazione esterna con cavo': 'Squat con manubri',
    'Sollevamento facciale': 'Squat con Manubri su Panca',
    'Camminata del contadino': 'Step-Up con Manubri',
    'Curl delle dita': 'Stretching Dinamico Schiena',
    'Dynamic Chest Stretch': 'Stretching Dinamico Petto',
    'EZ-Bar Curl': 'Curl con Bilanciere EZ',
    'EZ-Bar Skullcrusher': 'Estensioni per tricipiti con bilanciere EZ',
    'Elbow Circles': 'Circonduzioni delle braccia (gomiti)',
    'Elbow to Knee': 'Gomito al ginocchio (addominali)',
    'Elbows Back': 'Tirate indietro dei gomiti',
    'Elevated Back Lunge': 'Affondo posteriore rialzato',
    'Elevated Cable Rows': 'Rematore al cavo con rialzo',
    'Elliptical Trainer': 'Ellittica',
    'Exercise Ball Crunch': 'Crunch su palla svizzera',
    'Exercise Ball Pull-In': 'Trazioni con palla svizzera (ginocchia al petto)',
    'Extended Range One-Arm Kettlebell Floor Press': 'Floor press a un braccio con kettlebell (ampio raggio)',
    'External Rotation': 'Rotazione esterna con manubrio',
    'Salti veloci': 'Affondo dinamico con manubri',
    'Flat Bench Cable Flyes': 'Croci ai cavi su panca piana',
    'Flat Bench Leg Pull-In': 'Pull-in gambe su panca piana',
    'Flat Bench Lying Leg Raise': 'Sollevamento gambe sdraiato su panca piana',
    'Flexor Incline Dumbbell Curls': 'Curl manubri su panca inclinata (presa inversa)',
    'Floor Glute-Ham Raise': 'Stacco Ginocchia-Tendini',
    'Floor Press': 'Panca a Terra',
    'Floor Press con catene': 'Panca a Terra con Catene',
    'Flutter Kicks': 'Calci Alternati',
    'Foot-SMR': 'Automassaggio Piede',
    'Forward Drag with Press': 'Trazione Frontale con Spinta',
    'Frankenstein Squat': 'Squat Frankenstein',
    'Freehand Jump Squat': 'Salto con Squat a Corpo Libero',
    'Frog Hops': 'Salti a Rana',
    'Frog Sit-Ups': 'Addominali a Rana',
    'Stiramento e allungamento della schiena': 'Squat frontale con bilanciere su panca',
    'Front Box Jump': 'Salto sul box frontale',
    'Squat con martello': 'Alzate frontali al cavo',
    'Curl con martello': 'Salti frontali a ostacolo',
    'Front Leg Raises': 'Alzate Gambe Frontali',
    'Front Plate Raise': 'Alzate Piatto Frontali',
    'Front Raise And Pullover': 'Alzate Frontali e Pullover con Bilanciere',
    'Front Squat (Clean Grip)': 'Squat Frontale (Presa Clean)',
    'Front Squats With Two Kettlebells': 'Squat Front con due kettlebell',
    'Full Range-Of-Motion Lat Pulldown': 'Lat machine a tutto raggio',
    'Gironda Sternum Chins': 'Trazioni Gironda per lo sterno',
    'Equilibrio di Snatch con sollevamento': 'Glute Ham Raise',
    'Spinta sul sacco pesante': 'Slancio Glutei',
    'Curl con cavo alto': 'Squat a Calice',
    'Cerchi di bacino (prono)': 'Good Morning',
    'Estensione di bacino con cinture': 'Good Morning dai Supporti',
    'Flessione dei fianchi con cinghia': 'Crunch Chin Gorilla',
    'Abbraccia una palla': 'Groiners',
    'Hamstring-SMR': 'Foam Roller Ischiocrurali',
    'Stiramento dei hamstring': 'Stiramento Ischiolinguali',
    'Push-up in stile handstand': 'Piegamenti Verticali',
    'Hang Clean - Sotto le ginocchia': 'Clean in Hang - Sotto le ginocchia',
    'Hang Snatch': 'Strappo in Hang',
    'Hang Snatch - Below Knees': 'Stacco con Slancio da Sotto le Ginocchia',
    'Hanging Leg Raise': 'Sollevamento Gambe alla Sbarra',
    'Incline Dumbbell Flyes - Con Un Twist': 'Pike alla Sbarra',
    'Sollevamento dei fianchi con cinghia': 'Ponte Glutei con Fascia',
    'Abbraccia le ginocchia al petto': 'Tirata Ginocchia al Petto',
    'Salti tra ostacoli': 'Corsa Ostacoli',
    'Internal Rotation with Band': 'Iperestensioni Lombar',
    'Hyperextensions con nessuna panca di estensione iperestensiva': 'Iperestensioni a terra',
    'Stiramento dell\'IT Band e dei glutei': 'Stretching IT Band e Glutei',
    'Trattamento dell\'IT Tract-SMR': 'Foam Rolling IT Band',
    'Incline Barbell Triceps Extension': 'Estensioni Tricipiti con Bilanciere su Panca Inclinata',
    'Esercizio di gola isometrico - Fronte e dietro': 'Trazioni su Panca Inclinata',
    'Esercizio dei Wipers isometrici': 'Croci Alte ai Cavi',
    'Incline Dumbbell Curl': 'Curl Manubri su Panca Inclinata',
    'Jerk Balance': 'Panca Inclinata con Manubri',
    'Jogging, Treadmill': 'Curl Inclinato con Manubri per Bicipiti',
    'Incline Push-Up': 'Push-Up Inclinati',
    'Incline Push-Up Close-Grip': 'Push-Up Inclinati a Presa Stretta',
    'Incline Push-Up Depth Jump': 'Push-Up Pliometrici Inclinati con Balzo',
    'Incline Push-Up Medium': 'Push-Up Inclinati Presa Media',
    'Incline Push-Up Reverse Grip': 'Push-Up Inclinati Presa Supina',
    'Incline Push-Up Wide': 'Push-Up Inclinati Presa Larga',
    'Intermediate Groin Stretch': 'Stretching Inguine Intermedio',
    'Intermediate Hip Flexor and Quad Stretch': 'Stretching Intermedio Flessori dell\'Anca e Quadricipiti',
    'Inverted Row': 'Rematore Inverso',
    'Inverted Row con Straps': 'Rematore Inverso con Cinghie',
    'Iron Cross': 'Croce di Ferro',
    'Iron Crosses (stiramento)': 'Stretching Croce di Ferro',
    'Isometric Chest Squeezes': 'Spremitura Isometrica al Petto',
    'Knee Across The Body': 'JM Press',
    'Knee Circles': 'Sit-up a V (Jackknife Sit-up)',
    'Jefferson Squats': 'Squat Jefferson',
    'Carico del Keg': 'Sollevamento Keg',
    'Kettlebell Arnold Press': 'Arnold Press con Kettlebell',
    'Kettlebell Figure 8': 'Figure 8 con Kettlebell',
    'Kettlebell One-Legged Deadlift': 'Stacco a una gamba con Kettlebell',
    'Kettlebell Pass Between The Legs': 'Figure 8 con Kettlebell',
    'Kettlebell Pirate Ships': 'Slancio Rotatorio del Kettlebell (Navi Pirata)',
    'Kettlebell Pistol Squat': 'Pistol Squat con Kettlebell',
    'Kettlebell Seated Press': 'Kettlebell Press Seduto',
    'Kettlebell Turkish Get-Up (Lunge style)': 'Kettlebell Turkish Get-Up (Stile Affondo)',
    'Kettlebell Turkish Get-Up (Squat style)': 'Turkish Get-Up con Kettlebell (Stile Squat)',
    'Kettlebell Windmill': 'Windmill con Kettlebell',
    'Knee/Hip Raise On Parallel Bars': 'Sollevamento Gambe alle Parallele',
    'Knee Tuck Jump': 'Salto Ginocchia al Petto',
    'Kneeling Arm Drill': 'Drill Braccia in Ginocchio',
    'Kneeling Cable Crunch With Alternating Oblique Twists': 'Crunch ai Cavi in Ginocchio con Torsioni Oblique Alternate',
    'Kneeling Cable Triceps Extension': 'Estensioni Tricipiti ai Cavi in Ginocchio',
    'Kneeling Forearm Stretch': 'Stretching Avambracci in Ginocchio',
    'Kneeling High Pulley Row': 'Rematore Alto al Cavo in Ginocchio con Corda',
    'Kneeling Hip Flexor': 'Stretching Flessori Anca in Ginocchio',
    'Kneeling Jump Squat': 'Jump Squat in Ginocchio',
    'Kneeling Single-Arm High Pulley Row': 'Rematore Alto al Cavo in Ginocchio Monobraccio',
    'Kneeling Squat': 'Squat in Ginocchio',
    'Landmine 180\'s': 'Landmine 180°',
    'Landmine Linear Jammer': 'Landmine Jammer Lineare',
    'Lateral Bound': 'Balzo Laterale',
    'Lateral Box Jump': 'Box Jump Laterale',
    'Lateral Cone Hops': 'Salti Laterali ai Coni',
    'Lateral Raise - With Bands': 'Alzate Laterali con Elastici',
    'Latissimus Dorsi-SMR': 'Auto-Massaggio Miofasciale Dorsale',
    'Leg Extensions': 'Leg Extension',
    'Leg Lift': 'Slanci Gambe Indietro',
    'Lying Cable Curl': 'Leg Press',
    'Lying Cambered Barbell Row': 'Crunch Inverso',
    'Lying Close-Grip Bar Curl On High Pulley': 'Chest Press alla Macchina',
    'Lying Close-Grip Barbell Triceps Extension Behind The Head': 'Stacco con Macchina Leverage',
    'Lying Close-Grip Barbell Triceps Press To Chin': 'Chest Press Declinato alla Macchina Leverage',
    'Leverage High Row': 'High Row alla Macchina Leverage',
    'Leverage Incline Chest Press': 'Chest Press Inclinato alla Macchina Leverage',
    'Leverage Iso Row': 'Rematore Iso-laterale alla Macchina Leverage',
    'Leverage Shoulder Press': 'Shoulder Press con Macchina (Leverage)',
    'Leverage Shrug': 'Scrollate con Macchina (Leverage)',
    'Linear 3-Part Start Technique': 'Tecnica di Partenza a 3 Fasi (Lineare)',
    'Linear Acceleration Wall Drill': 'Drill al Muro per Accelerazione Lineare',
    'Linear Depth Jump': 'Salto in Basso Lineare (Linear Depth Jump)',
    'Guarda il soffitto': 'Arco Dorsale in Ginocchio',
    'Low Cable Triceps Extension': 'Estensione Tricipiti ai Cavi Bassi',
    'Low Pulley Row To Neck': 'Rematore al Cavo Basso al Collo',
    'Lower Back-SMR': 'SMR Lombare',
    'Lower Back Curl': 'Curl Lombare',
    'Lunge Pass Through': 'Affondo con Passaggio Kettlebell',
    'Lunge Sprint': 'Affondo Sprint',
    'Lying Bent Leg Groin': 'Adduzione Isometrica Gambe Piegate da Supino',
    'Lying Crossover': 'Stretching Crossover PNF (da Supino)',
    'Lying Dumbbell Tricep Extension': 'French Press con Manubri (su Panca Piana)',
    'Lying Face Down Plate Neck Resistance': 'Estensione del Collo con Disco (Prono)',
    'Lying Face Up Plate Neck Resistance': 'Flessione del Collo con Disco (Supino)',
    'Lying Glute': 'Allungamento Gluteo Supino Assistito',
    'Lying Hamstring': 'Allungamento Ischiocrurale Supino Assistito',
    'Lying Leg Curls': 'Leg Curl Prono',
    'Lying Machine Squat': 'Squat Orizzontale Macchina',
    'Lying Prone Quadriceps': 'Estensione Quadriceps Sdraiato',
    'Lying Rear Delt Raise': 'Alzate Posteriori Deltoidi Sdraiato',
    'Lying Supine Dumbbell Curl': 'Curl Manubri Supini Sdraiato',
    'Lying T-Bar Row': 'Rematore T-Bar Sdraiato',
    'Machine Bench Press': 'Panca Piana Macchina',
    'Machine Bicep Curl': 'Curl per bicipiti alla macchina',
    'Machine Preacher Curls': 'Preacher Curl alla macchina',
    'Machine Shoulder (Military) Press': 'Lento avanti alla macchina',
    'Machine Triceps Extension': 'Estensione tricipiti alla macchina',
    'Medicine Ball Chest Pass': 'Passaggio palla medica al petto',
    'Medicine Ball Full Twist': 'Torsioni Complete con Palla Medica',
    'Medicine Ball Scoop Throw': 'Lancio Esplosivo Palla Medica Indietro',
    'Middle Back Shrug': 'Scrollate Incline per Dorsali Medi',
    'Middle Back Stretch': 'Allungamento della Schiena Media',
    'Mixed Grip Chin': 'Trazioni a Presa Mista',
    'Narrow Stance Hack Squats': 'Hack Squat Stance Stretto',
    'Narrow Stance Squats': 'Squat Stance Stretto',
    'Neck-SMR': 'SMR per il Collo',
    'Oblique Crunches - On The Floor': 'Crunch Obliquo a Terra',
    'Olympic Squat': 'Squat Olimpico',
    'On-Your-Back Quad Stretch': 'Stretching Quadricipite Supino',
    'On Your Side Quad Stretch': 'Stretching Quadricipite Laterale',
    'One-Arm Dumbbell Row': 'Rematore con Manubrio Singolo',
    'One-Arm Flat Bench Dumbbell Flye': 'Croci Panca Piana Manubrio Singolo',
    'One-Arm Incline Lateral Raise': 'Alzate Laterali su Panca Inclinata a un Braccio',
    'Clean and Jerk': 'Girata e Spinta Kettlebell a un Braccio',
    'One-Arm Kettlebell Jerk': 'Kettlebell Jerk Monobraccio',
    'One-Arm Kettlebell Military Press To The Side': 'Military Press Laterale con Kettlebell Monobraccio',
    'One-Arm Kettlebell Para Press': 'Kettlebell Para Press Monobraccio',
    'One-Arm Kettlebell Push Press': 'Kettlebell Push Press Monobraccio',
    'One-Arm Kettlebell Row': 'Rematore Kettlebell Monobraccio',
    'One-Arm Kettlebell Snatch': 'Kettlebell Snatch Monobraccio',
    'One-Arm Kettlebell Split Jerk': 'Kettlebell Split Jerk Monobraccio',
    'One-Arm Kettlebell Split Snatch': 'Kettlebell Split Snatch Monobraccio',
    'One-Arm Kettlebell Swings': 'Kettlebell Swing Monobraccio',
    'One-Arm Long Bar Row': 'Rematore T-Bar Unilaterale',
    'One-Arm Medicine Ball Slam': 'Slam della Medicine Ball a un Braccio',
    'One-Arm Overhead Kettlebell Squats': 'Squat Overhead con Kettlebell a un Braccio',
    'One-Arm Side Deadlift': 'Stacco da Terra Laterale a un Braccio',
    'One-Arm Side Laterals': 'Alzate Laterali a un Braccio',
    'One-Legged Cable Kickback': 'Kickback al Cavo Monopodalico',
    'One Arm Against Wall': 'Stretching Dorsali a un Braccio al Muro',
    'One Arm Dumbbell Preacher Curl': 'Curl con Manubrio al Preacher (un braccio)',
    'One Arm Lat Pulldown': 'Lat Machine un Braccio (singolo)',
    'One Arm Pronated Dumbbell Triceps Extension': 'Estensione Tricipiti con Manubrio Pronato (un braccio)',
    'One Arm Supinated Dumbbell Triceps Extension': 'Estensione Tricipiti con Manubrio Supinato (un braccio)',
    'One Half Locust': 'Allungamento della Mezza Locusta',
    'One Handed Hang': 'Sospensione Monobraccio',
    'One Knee To Chest': 'Allungamento Ginocchio al Petto',
    'Otis-Up': 'Sit-Up Ponderato (Otis-Up)',
    'Overhead Cable Curl': 'Curl ai Cavi Sovratesta',
    'Overhead Lat': 'Allungamento Lat Sovratesta Assistito',
    'Overhead Slam': 'Slam della Palla Medica Sovratesta',
    'Press Sit-Up': 'Squat Sovratesta',
    'Prone Manual Hamstring': 'Stiramento Sopra la Testa',
    'Prowler Sprint': 'Stretching Tricipiti Overhead (Assistito)',
    'Pull Through': 'Pallof Press',
    'Pallof Press Con Rotazione': 'Pallof Press con Rotazione',
    'Push-Up Wide': 'Curl Polsi Pronato su Panca',
    'Palme-Down Wrist Curl Over A Bench': 'Curl polsi prono su panca',
    'Palms-Up Dumbbell Wrist Curl Over A Bench': 'Curl polsi supino con manubri su panca',
    'Parallel Bar Dip': 'Dip alle parallele',
    'Pelvic Tilt Into Bridge': 'Inclinazione pelvica e ponte',
    'Peroneals-SMR': 'SMR peronieri',
    'Peroneals Stretch': 'Stretching Peronei',
    'Physioball Hip Bridge': 'Hip Thrust su Fitball',
    'Pin Presses': 'Panca su Pin',
    'Stiramento dei quadricipiti': 'SMR Piriforme con Foam Roller',
    'SMR dei quadriceps': 'Plank',
    'Salto veloce': 'Pinch con Dischi',
    'Consegna al carrello': 'Russian Twist con Disco',
    'Sollevamento del carrello con cinture': 'Scivolamenti per Femorali (Hamstring Slides)',
    'Plyo Kettlebell Pushups': 'Piegamenti Pliometrici con Kettlebell',
    'Plyo Push-up': 'Push-up Pliometrici (Plyo Push-up)',
    'Posterior Tibialis Stretch': 'Stretching del Tibiale Posteriore',
    'Power Snatch': 'Strappo (Power Snatch)',
    'Power Snatch da Blocchi': 'Strappo dai Blocchi (Power Snatch from Blocks)',
    'Power Stairs': 'Spinta Carico su Scalinata (Power Stairs)',
    'Preacher Curl': 'Curl alla Panca Scott (Preacher Curl)',
    'Pullups': 'Trazioni',
    'Push-Ups - Close Triceps Position': 'Piegamenti a Terra Presa Stretta (Tricipiti)',
    'Rickshaw Carry': 'Piegamenti a Terra con Piedi Rialzati',
    'Rickshaw Deadlift': 'Push-up su Fitball con Piedi Rialzati',
    'Ring Dips': 'Push Press',
    'Push Press - Behind the Neck': 'Push Press Dietro la Nuca',
    'Pushups': 'Piegamenti sulle Braccia',
    'Pushups (Posizioni di mano stretta e larga)': 'Piegamenti (Presa Stretta e Larga)',
    'Piramide': 'Pike con Fitball',
    'Rack Pulls': 'Mezzi stacchi al rack (Rack Pull)',
    'Rear Leg Raises': 'Slanci posteriori in quadrupedia',
    'Recumbent Bike': 'Cyclette orizzontale',
    'Return Push from Stance': 'Spinte reattive da posizione atletica',
    'Reverse Band Bench Press': 'Panca piana con elastici in scarico (Reverse Band)',
    'Reverse Band Deadlift': 'Stacco da terra con elastici in scarico (Reverse Band)',
    'Reverse Band Power Squat': 'Power Squat con elastici in scarico (Reverse Band)',
    'Reverse Barbell Preacher Curls': 'Curl bicipiti presa inversa alla panca Scott con bilanciere EZ',
    'Reverse Cable Curl': 'Curl ai cavi bassi con presa inversa',
    'Reverse Crunch': 'Crunch Inverso',
    'Reverse Flyes': 'Alzate laterali prone su panca inclinata',
    'Reverse Grip Bent-Over Rows': 'Rematore con bilanciere a presa supina',
    'Reverse Grip Triceps Pushdown': 'Pushdown tricipiti a presa inversa',
    'Reverse Hyperextension': 'Reverse Hyper',
    'Reverse Machine Flyes': 'Rear Delt Machine',
    'Reverse Plate Curls': 'Curl con disco a presa inversa',
    'Reverse Triceps Bench Press': 'Panca piana presa stretta inversa',
    'Rhomboids-SMR': 'Rilascio miofasciale romboidi (SMR)',
    'Rocking Standing Calf Raise': 'Calf Raise in piedi con dondolio',
    'Rocky Pull-Ups/Pulldowns': 'Trazioni alla Rocky',
    'Romanian Deadlift': 'Stacco Rumeno (RDL)',
    'Rope Climb': 'Salita della fune',
    'Rope Crunch': 'Crunch al cavo alto con corda',
    'Rope Jumping': 'Salto della corda',
    'Rope Straight-Arm Pulldown': 'Pulldown a braccia tese con corda',
    'Round The World Shoulder Stretch': 'Dislocazioni spalle con bastone',
    'Rowing, Stationary': 'Vogatore',
    'Runner\'s Stretch': 'Stretching del Corridore',
    'Running, Treadmill': 'Corsa su Tapis Roulant',
    'Sandbag Load': 'Caricamento Sandbag',
    'Scapular Pull-Up': 'Trazioni Scapolari',
    'Scissor Kick': 'Sforbiciata addominale (Scissor Kick)',
    'Shoulder Press - Con Bande': 'Affondi saltati (Scissors Jump)',
    'Seated Band Hamstring Curl': 'Leg Curl seduto con elastico',
    'Seated Barbell Military Press': 'Military Press da seduto con bilanciere',
    'Seated Barbell Twist': 'Twist del busto seduto con bilanciere',
    'Seated Bent-Over One-Arm Dumbbell Triceps Extension': 'Kickback manubrio singolo seduto',
    'Seated Bent-Over Rear Delt Raise': 'Alzate laterali a 90° da seduto',
    'Seated Bent-Over Two-Arm Dumbbell Triceps Extension': 'Kickback manubri a due braccia seduto',
    'Seated Cable Rows': 'Pulley basso',
    'Seated Calf Raise': 'Calf Machine seduto',
    'Seated Calf Stretch': 'Stretching polpacci da seduto',
    'Seated Dumbbell Curl': 'Curl manubri da seduto',
    'Seated Dumbbell Inner Biceps Curl': 'Curl manubri seduto (focus bicipite interno)',
    'Seated Dumbbell Palms-Down Wrist Curl': 'Wrist curl con manubri presa prona',
    'Seated Dumbbell Palms-Up Wrist Curl': 'Wrist curl con manubri presa supina',
    'Seated Front Deltoid': 'Stretching deltoidi anteriori assistito',
    'Seated Glute': 'Stretching Glutei Seduto (Tecnica PNF)',
    'Seated Good Mornings': 'Good Morning da Seduto',
    'Seated Hamstring': 'Stretching Femorali Seduto (Tecnica PNF)',
    'Seated Hamstring and Calf Stretch': 'Stretching Femorali e Polpacci con Fascia',
    'Seated Head Harness Neck Resistance': 'Estensioni Collo con Head Harness da Seduto',
    'Seated Leg Curl': 'Leg Curl Seduto',
    'Seated Leg Tucks': 'Addominali a libretto su panca',
    'Seated One-Arm Dumbbell Palms-Down Wrist Curl': 'Wrist Curl inverso singolo con manubrio',
    'Seated One-Arm Dumbbell Palms-Up Wrist Curl': 'Wrist Curl singolo con manubrio',
    'Seated One-arm Cable Pulley Rows': 'Pulley basso singolo',
    'Seated Palms-Down Barbell Wrist Curl': 'Wrist Curl con bilanciere a presa prona da seduti',
    'Seated Side Lateral Raise': 'Alzate laterali con manubri da seduti',
    'Seated Triceps Press': 'Estensioni dei tricipiti con manubrio da seduti',
    'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl': 'Wrist Curl al cavo basso a presa supina',
    'Shotgun Row': 'Rematore al cavo basso singolo (Shotgun Row)',
    'Shoulder Circles': 'Circonduzioni delle spalle',
    'Shoulder Raise': 'Scrollate di spalle (Shoulder Raise)',
    'Shoulder Stretch': 'Stretching deltoide posteriore',
    'Side-Lying Floor Stretch': 'Stretching laterale a terra sul fianco',
    'Side Bridge': 'Side Bridge (Ponte laterale)',
    'Side Hop-Sprint': 'Salti laterali con sprint',
    'Side Jackknife': 'Side Jackknife (Chiusura a libro laterale)',
    'Side Lateral Raise': 'Alzate laterali con manubri',
    'Side Laterals to Front Raise': 'Alzate laterali e frontali combinate',
    'Side Leg Raises': 'Slanci laterali delle gambe in piedi',
    'Side Lying Groin Stretch': 'Stretching adduttori in decubito laterale',
    'Side Neck Stretch': 'Stretching laterale del collo',
    'Side Standing Long Jump': 'Salto in lungo laterale',
    'Side To Side Chins': 'Trazioni alla sbarra Side-to-Side',
    'Side Wrist Pull': 'Stretching del polso incrociato',
    'Side to Side Box Shuffle': 'Shuffle laterale su box',
    'Single-Arm Push-Up': 'Piegamenti a un braccio',
    'Single-Cone Sprint Drill': 'Sprint d\'agilità attorno al cono',
    'Spider Crawl': 'Salti monopodalici in avanzamento',
    'Spider Curl': 'Salti laterali monopodalici',
    'Spinal Stretch': 'Leg extension singola',
    'Split Clean': 'Salto dinamico su box (monolaterale)',
    'Snatch a scissione': 'Calciata dietro monopodalica esplosiva',
    'Squat con dumbbell a scissione': 'Ponte per i glutei a una gamba',
    'Squat a scissione': 'Step-up esplosivo su box',
    'Sit-Up': 'Sit-up',
    'Sit Squats': 'Box Squat Parziale',
    'Skating': 'Pattinaggio (Cardio)',
    'Sled Drag - Harness': 'Traino della Slitta con Imbracatura',
    'Sled Overhead Backward Walk': 'Camminata Indietro con Slitta Overhead',
    'Sled Overhead Triceps Extension': 'Estensioni Tricipiti con Slitta sopra la Testa',
    'Sled Push': 'Spinta Sled',
    'Sled Reverse Flye': 'Reverse Fly Sled',
    'Sled Row': 'Rematore Sled',
    'Sledgehammer Swings': 'Swings con Mazza',
    'Smith Machine Behind the Back Shrug': 'Scrollate con Bilanciere Smith dietro la Schiena',
    'Smith Machine Bent Over Row': 'Rematore con Bilanciere Smith a Busto Flesso',
    'Smith Machine Calf Raise': 'Calf Raise alla Smith Machine',
    'Smith Machine Close-Grip Bench Press': 'Panca Piana Presa Stretta alla Smith Machine',
    'Smith Machine Decline Press': 'Panca declinata alla Smith Machine',
    'Smith Machine Incline Bench Press': 'Panca inclinata alla Smith Machine',
    'Smith Machine One-Arm Upright Row': 'Rematore verticale a un braccio alla Smith Machine',
    'Smith Machine Overhead Shoulder Press': 'Shoulder Press alla Smith Machine',
    'Smith Machine Pistol Squat': 'Pistol Squat alla Smith Machine',
    'Smith Machine Reverse Calf Raises': 'Sollevamenti Tibiali alla Smith Machine',
    'Smith Machine Squat': 'Squat alla Smith Machine',
    'Smith Machine Stiff-Legged Deadlift': 'Stacchi a Gambe Tese alla Smith Machine',
    'Smith Machine Upright Row': 'Rematore Verticale alla Smith Machine',
    'Snatch': 'Strappo Olimpico',
    'Snatch Deadlift': 'Stacco da Terra da Strappo',
    'Snatch Pull': 'Tirata di Strappo',
    'Snatch from Blocks': 'Strappo dai Blocchi',
    'Squat con Banda': 'Squat con Elastici',
    'Squat con Mover di Piatto': 'Squat con Spostamento Laterale e Disco',
    'Standing Alternating Dumbbell Press': 'Spinte Alternate con Manubri in Piedi',
    'Standing Barbell Calf Raise': 'Calf Raise in Piedi con Bilanciere',
    'Standing Barbell Press Behind Neck': 'Lento Dietro con Bilanciere in Piedi',
    'Standing Bent-Over One-Arm Dumbbell Triceps Extension': 'Kickback Tricipiti con Manubrio a un Braccio, Busto Flesso in Avanti',
    'Sumo Deadlift con catene': 'Kickback Tricipiti con Due Manubri, Busto Flesso in Avanti',
    'Standing Biceps Cable Curl': 'Curl Bicipiti al Cavo Basso in Piedi',
    'Standing Biceps Stretch': 'Stretching Bicipiti in Piedi',
    'Standing Bradford Press': 'Bradford Press in Piedi',
    'Standing Cable Lift': 'Sollevamento ai Cavi in Piedi',
    'Standing Cable Wood Chop': 'Wood Chop ai Cavi in Piedi',
    'Standing Calf Raises': 'Calf Raises in Piedi alla Macchina',
    'Standing Concentration Curl': 'Curl di Concentrazione in Piedi',
    'Standing Dumbbell Calf Raise': 'Calf Raises con Manubri in Piedi',
    'Standing Dumbbell Press': 'Shoulder Press con Manubri in Piedi',
    'Standing Dumbbell Reverse Curl': 'Reverse Curl con Manubri in Piedi',
    'Standing Dumbbell Straight-Arm Front Delt Raise Above Head': 'Alzate Frontali con Manubri a Braccia Tese Sopra la Testa',
    'Standing Dumbbell Triceps Extension': 'French Press in Piedi con Manubrio',
    'Standing Dumbbell Upright Row': 'Tirate al Mento con Manubri in Piedi',
    'Standing Elevated Quad Stretch': 'Stretching del Quadricipite in Piedi con Appoggio',
    'Standing Front Barbell Raise Over Head': 'Alzate Frontali con Bilanciere Sopra la Testa',
    'Standing Gastrocnemius Calf Stretch': 'Stretching Polpaccio Gastrocnemio in Piedi',
    'Standing Hamstring and Calf Stretch': 'Stretching Femorali e Polpacci in Piedi',
    'Standing Hip Circles': 'Circonduzioni Anca in Piedi',
    'Standing Hip Flexors': 'Stretching Flessori Anca in Piedi',
    'Standing Inner-Biceps Curl': 'Curl Manubri con Rotazione in Piedi',
    'Standing Lateral Stretch': 'Stretching Laterale in Piedi',
    'Standing Leg Curl': 'Leg Curl in Piedi (Singolo)',
    'Standing Long Jump': 'Salto in Lungo da Fermo',
    'Standing Low-Pulley Deltoid Raise': 'Alzate Laterali al Cavo Basso in Piedi',
    'Standing Low-Pulley One-Arm Triceps Extension': 'Estensioni Tricipiti sopra la Testa, Cavo Basso, Monobraccio',
    'Standing Military Press': 'Lento Avanti in Piedi',
    'Standing Olympic Plate Hand Squeeze': 'Squeeze con Dischi Olimpici',
    'Standing One-Arm Cable Curl': 'Curl Cavo Basso Monobraccio',
    'Standing One-Arm Dumbbell Triceps Extension': 'French Press Manubrio Singolo in Piedi',
    'Standing Overhead Barbell Triceps Extension': 'French Press con Bilanciere in Piedi',
    'Standing Pelvic Tilt': 'Tilt Pelvico in Piedi',
    'Stiramento verso l\'alto': 'Stretching Soleo e Tendine d\'Achille in Piedi',
    'Sollevamento con V-Bar': 'Toccata Punte Piedi in Piedi',
    'Lancio con due braccia in piedi': 'Lancio Palla Medica da in Piedi',
    'Salita con sollevamento di ginocchio': 'Step-Up con Ginocchio al Petto',
    'Step Mill': 'Stair Climber',
    'Deadlift con barra rigida': 'Stacco Rumeno',
    'Stiff-Legged Dumbbell Deadlift': 'Stacchi a Gambe Tese con Manubri',
    'Stomach Vacuum': 'Vacuum Addominale',
    'Straight-Arm Dumbbell Pullover': 'Pullover con Manubrio a Braccia Tese',
    'Straight Bar Bench Mid Rows': 'Rematore al Bilanciere su Panca',
    'Straight Raises on Incline Bench': 'Alzate Frontali su Panca Inclinata',
    'Stride Jump Crossover': 'Salto Crossover su Box',
    'Sumo Deadlift': 'Stacco Sumo',
    'Supine Chest Throw': 'Lancio Med Ball Petto Supino',
    'Supine One-Arm Overhead Throw': 'Lancio Med Ball Sopra la Testa Unilaterale da Supino',
    'Supine Two-Arm Overhead Throw': 'Lancio Med Ball Sopra la Testa Bilaterale da Supino',
    'Suspended Fallout': 'Ab Rollout in Sospensione',
    'Suspended Push-Up': 'Push-Up in Sospensione',
    'Suspended Row': 'Rematore in Sospensione',
    'Suspended Split Squat': 'Affondo Bulgaro in Sospensione',
    'T-Bar Row with Handle': 'Rematore T-Bar con Maniglia',
    'The Straddle': 'Spaccata Seduta',
    'Thigh Abductor': 'Abduzioni Machine',
    'Thigh Adductor': 'Adduzioni Machine',
    'Tire Flip': 'Flipping del Pneumatico',
    'Toe Touchers': 'Crunch con Tocco delle Punte',
    'Torso Rotation': 'Rotazione del Busto con Palla Medica',
    'Trail Running/Walking': 'Trail Running/Trekking',
    'Trap Bar Deadlift': 'Stacco con Trap Bar',
    'Tricep Dumbbell Kickback': 'Kickback con manubri per tricipiti',
    'Tricep Side Stretch': 'Stretching laterale per tricipiti',
    'Triceps Pushdown - Rope Attachment': 'Pushdown per tricipiti con corda',
    'Triceps Pushdown - V-Bar Attachment': 'Pushdown per tricipiti con barra a V',
    'Triceps Stretch': 'Stretching per tricipiti',
    'Tuck Crunch': 'Crunch a Caramella',
    'Two-Arm Kettlebell Jerk': 'Jerk a Kettlebell a Due Braccia',
    'Two-Arm Kettlebell Military Press': 'Military Press a Kettlebell a Due Braccia',
    'Two-Arm Kettlebell Row': 'Rematore con Kettlebell a Due Braccia',
    'Underhand Cable Pulldowns': 'Trazioni al Cavo Presa Inversa',
    'Upper Back-Leg Grab': 'Afferraggio Upper Back-Leg',
    'Upper Back Stretch': 'Stretching Upper Back',
    'Upright Barbell Row': 'Rematore con Bilanciere in Alto',
    'Upright Cable Row': 'Rematore al cavo alto',
    'Svasso verticale': 'Lancio con palla medica',
    'Camminata, Tapis roulant': 'Salto a stella',
    'Weighted Ball Hyperextension': 'Iperestensione con palla medica',
    'Weighted Ball Side Bend': 'Flessione laterale con palla medica',
    'Weighted Bench Dip': 'Dip su panca ponderato',
    'Weighted Jump Squat': 'Squat con Salto e Pesi',
    'Weighted Pull Ups': 'Trazioni alla Sbarra con Pesi',
    'Weighted Sissy Squat': 'Sissy Squat con Pesi',
    'Weighted Sit-Ups - Con Banda': 'Trazioni alla Chest con Elastico',
    'Weighted Squat': 'Squat con Pesi',
    'Wide-Grip Decline Barbell Pullover': 'Pullover con Bilanciere Presa Larga Declinato',
    'Wide-Grip Lat Pulldown': 'Lat Machine Presa Larga',
    'Wide Stance Stiff Legs': 'Stiff Leg Romanian Deadlift a Gambe Larghe',
    'Wind Sprints': 'Sprint a Vento',
    'Windmills': 'Corsa di Molinella',
    'World\'s Greatest Stretch': 'Allungamento del Miglior Esercizio del Mondo',
    'Wrist Circles': 'Circonduzioni Polsi',
    'Wrist Roller': 'Rotazioni Polsi con Manubrio',
    'Wrist Rotations with Straight Bar': 'Rotazioni Polsi con Bilanciere',
    'Yoke Walk': 'Camminata Yoke',
    'Zercher Squats': 'Squat Zercher',
    'Zottman Curl': 'Curl Zottman',
  };
}
