// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static FirebaseOptions get web => FirebaseOptions(
  apiKey: const String.fromEnvironment('FIREBASE_KEY_WEB', defaultValue: 'AIzaSyAM_tEdZDeweZHhnz31ZYWDNBS-SA3ftAg'),
    appId: '1:969748256853:web:eaf849a2bd42b2dc115cdc',
    messagingSenderId: '969748256853',
    projectId: 'palestrai-5856f',
    authDomain: 'palestrai-5856f.firebaseapp.com',
    storageBucket: 'palestrai-5856f.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_KEY_ANDROID', defaultValue: 'AIzaSyC9STGUH1f6Pt52ZBVHNk1a3NOPxLptX6c'),
    appId: '1:969748256853:android:a13558c200a737aa115cdc',
    messagingSenderId: '969748256853',
    projectId: 'palestrai-5856f',
    storageBucket: 'palestrai-5856f.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_KEY_IOS', defaultValue: 'AIzaSyDPWfO1qoglQ4Cfg-ogCt9_9nTJYL_rSQo'),
    appId: '1:969748256853:ios:40ec81b8c2501cd5115cdc',
    messagingSenderId: '969748256853',
    projectId: 'palestrai-5856f',
    storageBucket: 'palestrai-5856f.firebasestorage.app',
    iosBundleId: 'com.example.palestra',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_KEY_IOS', defaultValue: 'AIzaSyDPWfO1qoglQ4Cfg-ogCt9_9nTJYL_rSQo'),
    appId: '1:969748256853:ios:40ec81b8c2501cd5115cdc',
    messagingSenderId: '969748256853',
    projectId: 'palestrai-5856f',
    storageBucket: 'palestrai-5856f.firebasestorage.app',
    iosBundleId: 'com.example.palestra',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_KEY_WEB', defaultValue: 'AIzaSyAM_tEdZDeweZHhnz31ZYWDNBS-SA3ftAg'),
    appId: '1:969748256853:web:d7c4a42d429a2aad115cdc',
    messagingSenderId: '969748256853',
    projectId: 'palestrai-5856f',
    authDomain: 'palestrai-5856f.firebaseapp.com',
    storageBucket: 'palestrai-5856f.firebasestorage.app',
  );
}
